[package]
name = "brainfuck_interpreter"
version = "0.1.0"
authors = ["Jan Krüger <jan.krueger.dev@outlook.com>"]
edition = "2018"
publish = false
license-file = "LICENSE"

[dependencies]
#clap = "2.33.1"
nom = "5.1.2"
